apiVersion: apps/v1
kind: Deployment
metadata:
  name: vproapp-deployment
  labels:
    app: vproapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vproapp
  template:
    metadata:
      labels:
        app: vproapp
    spec:
      containers:
      - name: vproapp
        image: vproapp/vprofileapp:latest
        ports:
        - containerPort: 8080
          name: vproapp-port
      initContainers:
      - name: init-db
        image: busybox:latest
        command: ["sh", "-c", "until nslookup vprodb.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for database service; sleep 2; done"]
      
      - name: init-cache
        image: busybox:latest
        command: ["sh", "-c", "until nslookup vprocache01.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for cache service; sleep 2; done"]
        
      - name: init-rmq
        image: busybox:latest
        command: ["sh", "-c", "until nslookup vpromq01.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for RabbitMQ service; sleep 2; done"]
