apiVersiob: networking.k8s.io/v1
kind: ingress
metadata: vproapp-ingress
spec:
  ingressClassname: nginx
  rules:
  - host: vproapp.ckdevopsgenie.online
    http:
      paths:
      - path: /
        pathtype: prefix
        backend:
          service:
            name: vproapp-service
            port:
              number: 8080


