def COLOR_MAP = [
    'SUCCESS': 'good',
    'FAILURE': 'danger',
]

pipeline {
    agent any
    tools {
        maven "MAVEN3.0"
        jdk "JDK17"
    }
    
        stage('deploy to prod')
        {
            steps{
                withAWS(credentials: 'awscreds_jenkinscicd', region: 'ap-south-1') {
                    sh 'aws ecs update-service --cluster vprofile-prod --service vprofile-app-service-prod --force-new-deployment '
                }
                 }
        }


    }

post {
    always {
        script {
            echo 'Sending build status to Slack...'
            slackSend channel: '#jenkinscicd', color: COLOR_MAP[currentBuild.currentResult], message: "*${currentBuild.currentResult}:* Job ${env.JOB_NAME} \n More info at : ${env.BUILD_NUMBER} ${env.BUILD_URL}"
        }
    }
}
}